server:
 port: 8082

spring:
  application:
    name: e-learning-microservice-rest-2
  cloud:
    config:
      discovery:
        enabled: true
        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    fetchRegistry: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
backend:
  admin:
    role: BACKEND_ADMIN
    username: backend_admin
    password: remember_to_change_me_by_external_property_on_deploy