server:
 port: 8081
 

spring:
  application:
    name: e-learning-microservice-rest-1
  cloud:
    config:
      discovery:
        enabled: true
security:
  user:
    password: password
        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    fetchRegistry: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/