server:
  port: 80

spring:
  application:
    name: e-learning-web
  cloud:
    config:
      discovery:
        enabled: true
        
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    fetchRegistry: false #set to false to not send the connection request each time (for instance when running a test case that doesn't need eureka)
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  context-path: /actuator
  security:
    role: ADMIN # ADMIN is the default role, but we explicitly set it. 
      

zuul:
  routes:
    service1:
      path: /api/service1/**
      url: http://localhost:8081/api/v1/service1
    service2:
      path: /api/service2/**
      url: http://localhost:8081/api/v1/service2

      
spring.social.facebook.app.id: 
spring.social.facebook.app.secret: 

spring.social.twitter.consumer.key: 
spring.social.twitter.consumer.secret: 

spring.social.linkedin.app.id: 
spring.social.linkedin.app.secret: 