server:
 port: 8888
 
spring:
  application:
    name: CONFIGSERVER
  cloud:
    config:
      server:
        uri: https://github.com/gustavoorsi/e-learning-spring-config-properties
        
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/